Repository bids-standard/bids-starter-kit, pull requests merged in 2018-08, with the labels that each got.

#73 Add good first issue to contributing guidelines
  CONTRIBUTING.md
Labels: community, documentation

#70 Add motivation and publications to README
  README.md
Labels: closing soon, community, documentation

#83 add archive of wiki to repo
  wiki-archives/bids-starter-kit-wiki-20180813.zip
Labels: funding, logistics

#81 Review and feedback on Patrick's final report
  reports/Google-2018-report.md
Labels: funding, logistics
